### ISSUE TITLE
does deletingCompactionStrategy support TWCS?

### ISSUE THREAD

**Issue by shendayu** [protectwise/cassandra-util#13]
hi  does deletingCompactionStrategy support TWCS?

**Comment by MightyE** [comment]
I haven't specifically tested it, but there should be no reason why not.  The underlying compactor is responsible for all the business logic about what files to compact, DCS just filters the records as they are being copied over to the new SSTable.  

Of course in TWCS sstables eventually stop compacting, to reclaim space / effect deletion from those files, user defined compaction would need to be used.
